# Generated by Django 5.2.4 on 2025-08-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Image',
        ),
    ]
