# Generated by Django 5.2.4 on 2025-09-18 22:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='gallery/'),
        ),
    ]
